@startuml
class Transacao {
    + Valor : decimal <<get>> <<set>>
}
Transacao --> "Id" Guid
Transacao o-> "DataHora" DateTime
Transacao --> "Tipo" TipoTransacao
Transacao --> "CarteiraId" Guid
Transacao o-> "Carteira" Carteira
@enduml
