// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UFRA.Bolaio.API.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202200704_ahseila")]
    partial class ahseila
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Bolao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fechamento");

                    b.Property<int>("MaxParticipantes")
                        .HasColumnType("integer")
                        .HasColumnName("max_participantes");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<Guid>("OrganizadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizador_id");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("partida_id");

                    b.Property<string>("Premio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("premio");

                    b.Property<decimal>("TaxaAdministrativa")
                        .HasColumnType("numeric")
                        .HasColumnName("taxa_administrativa");

                    b.Property<int>("TipoBolao")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_bolao");

                    b.Property<int>("TipoEsporte")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_esporte");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.Property<int>("Visibilidade")
                        .HasColumnType("integer")
                        .HasColumnName("visibilidade");

                    b.Property<int>("qtdParticipantes")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_participantes");

                    b.HasKey("Id")
                        .HasName("pk_boloes");

                    b.HasIndex("OrganizadorId")
                        .HasDatabaseName("ix_boloes_organizador_id");

                    b.HasIndex("PartidaId")
                        .HasDatabaseName("ix_boloes_partida_id");

                    b.ToTable("boloes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Carteira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("SaldoAtual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_atual");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_carteiras");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_carteiras_usuario_id");

                    b.ToTable("carteiras", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Palpites", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BolaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("bolao_id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<Guid>("ParticipanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("participante_id");

                    b.Property<int>("QtdCotas")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_cotas");

                    b.Property<Guid>("TransacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("transacao_id");

                    b.HasKey("Id")
                        .HasName("pk_palpites");

                    b.HasIndex("BolaoId")
                        .HasDatabaseName("ix_palpites_bolao_id");

                    b.HasIndex("ParticipanteId")
                        .HasDatabaseName("ix_palpites_participante_id");

                    b.HasIndex("TransacaoId")
                        .HasDatabaseName("ix_palpites_transacao_id");

                    b.ToTable("palpites", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataPartida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_partida");

                    b.Property<string>("ResultadoTimeA")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resultado_time_a");

                    b.Property<string>("ResultadoTimeB")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resultado_time_b");

                    b.Property<Guid>("TimeAId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_a_id");

                    b.Property<Guid>("TimeBId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_b_id");

                    b.HasKey("Id")
                        .HasName("pk_partidas");

                    b.HasIndex("TimeAId")
                        .HasDatabaseName("ix_partidas_time_a_id");

                    b.HasIndex("TimeBId")
                        .HasDatabaseName("ix_partidas_time_b_id");

                    b.ToTable("partidas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Times", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BandeiraUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bandeira_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sigla");

                    b.HasKey("Id")
                        .HasName("pk_times");

                    b.ToTable("times", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CarteiraId")
                        .HasColumnType("uuid")
                        .HasColumnName("carteira_id");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_transacoes");

                    b.HasIndex("CarteiraId")
                        .HasDatabaseName("ix_transacoes_carteira_id");

                    b.ToTable("transacoes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_salt");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Bolao", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Organizador")
                        .WithMany()
                        .HasForeignKey("OrganizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_boloes_usuarios_organizador_id");

                    b.HasOne("Domain.Entities.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_boloes_partidas_partida_id");

                    b.Navigation("Organizador");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("Domain.Entities.Carteira", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithOne("Carteira")
                        .HasForeignKey("Domain.Entities.Carteira", "UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_carteiras_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Palpites", b =>
                {
                    b.HasOne("Domain.Entities.Bolao", "Bolao")
                        .WithMany("Palpites")
                        .HasForeignKey("BolaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_palpites_boloes_bolao_id");

                    b.HasOne("Domain.Entities.Usuario", "Participante")
                        .WithMany()
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_palpites_usuarios_participante_id");

                    b.HasOne("Domain.Entities.Transacao", "Transacao")
                        .WithMany()
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_palpites_transacoes_transacao_id");

                    b.Navigation("Bolao");

                    b.Navigation("Participante");

                    b.Navigation("Transacao");
                });

            modelBuilder.Entity("Domain.Entities.Partida", b =>
                {
                    b.HasOne("Domain.Entities.Times", "TimeA")
                        .WithMany()
                        .HasForeignKey("TimeAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partidas_times_time_a_id");

                    b.HasOne("Domain.Entities.Times", "TimeB")
                        .WithMany()
                        .HasForeignKey("TimeBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partidas_times_time_b_id");

                    b.Navigation("TimeA");

                    b.Navigation("TimeB");
                });

            modelBuilder.Entity("Domain.Entities.Transacao", b =>
                {
                    b.HasOne("Domain.Entities.Carteira", "Carteira")
                        .WithMany("Transacoes")
                        .HasForeignKey("CarteiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transacoes_carteiras_carteira_id");

                    b.Navigation("Carteira");
                });

            modelBuilder.Entity("Domain.Entities.Bolao", b =>
                {
                    b.Navigation("Palpites");
                });

            modelBuilder.Entity("Domain.Entities.Carteira", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Carteira");
                });
#pragma warning restore 612, 618
        }
    }
}
