@UFRA.Bolao.API_HostAddress = https://localhost:7228

POST {{UFRA.Bolao.API_HostAddress}}/auth/login
Content-Type: application/json

{
  "email":"9joaovictor@gmail.com",
  "senha":"joao123"
}

###

POST {{UFRA.Bolao.API_HostAddress}}/auth/register
Content-Type: application/json

{
  "nome":"joao teste",
  "email":"9joaovictor@gmail.com",
  "senha":"joao123"
}
